@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "many1",
  "password": "123456",
  "email": "concac1@gmail.com",
  "avatarColor": "red",
  "avatarImage": "<add-a-base64-encoded-string>"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "many1",
  "password": "123456"
}

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "concac1@gmail.com"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/123213453543645
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "123asd",
  "confirmPassword": "123asd"
}
